### ISSUE TITLE
[PE-D][Tester E] Add command does not support "s/o"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14B-2/tp#165]
![image.png](https://raw.githubusercontent.com/sumomomomomo/ped/main/files/60fef02e-398d-4bb2-94b2-e40344947818.png)

e.g. Nagaratnam s/o Suppiah, which is a valid Singaporean Indian name (from https://culturalatlas.sbs.com.au/singaporean-culture/singaporean-culture-naming)

I believe this is a functionality bug, as "s/o" is a part of his name.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: sumomomomomo/ped#1

**Comment by FlyingDonkeys** [comment]
Good to support names with special characters in the future :)
