### ISSUE TITLE
[PE-D][Tester E] Phone number field does not allow specifying country codes with '+'

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14B-2/tp#167]
![image.png](https://raw.githubusercontent.com/sumomomomomo/ped/main/files/9083e3ca-e7e3-4907-9cb2-e174558d6d79.png)

As a TA, I am likely to have foreign students with no Singaporean phone number. Could be inconvenient for me to not be able to specify their country code for convenience in the phone number field.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: sumomomomomo/ped#2

**Comment by FlyingDonkeys** [comment]
Many exchange students I know in fact have Singaporean phone numbers, this is not a bug for our use cases.
