### ISSUE TITLE
[PE-D][Tester C] Sample data doesn't match the one given in the user guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14B-2/tp#173]
when the jar file is run, the sample data is different from what is given in the user guide.

![image.png](https://raw.githubusercontent.com/arnav-goel10/ped/main/files/b58b6fad-fc1b-4d6a-8de9-99672a33b6a1.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: arnav-goel10/ped#3

**Comment by FlyingDonkeys** [comment]
Since this tester sees this as the initial view, I will just screenshot this view and replace the current image with my screenshot. Fixed.
