### ISSUE TITLE
[PE-D][Tester E] clear command removes all data with no warning to the user

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14B-2/tp#180]
![image.png](https://raw.githubusercontent.com/sumomomomomo/ped/main/files/2070ec1f-5781-4c2b-9f5f-be64e593bc84.png)

As a TA, when I am trying to frantically manage my students' data and I mistype "clear" and press enter, all data is cleared with no warning. I could not find any way to restore the deleted data in the UG.

This could be improved by adding support for undo/redo, or adding a warning and confirmation for the user, before proceeding with deleting all data.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: sumomomomomo/ped#6

**Comment by FlyingDonkeys** [comment]
This warning: __WARNING: this operation is irreversible. You may lose all your data!__

has already been provided in the User Guide to indicate the nature of the ```clear``` command. If the user accidentally does the clear operation, it cannot be considered a bug to us.
