### ISSUE TITLE
[PE-D][Tester D] Minor typo with Markdown in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14B-2/tp#183]
Second Bullet point should include `Hans Bo` and `Bo Hans` rather than only wrapping the `Hans` 
![image.png](https://raw.githubusercontent.com/gnoossk/ped/main/files/850fcecb-6c2d-4943-bc34-afd555919a30.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: gnoossk/ped#5

**Comment by FlyingDonkeys** [comment]
Fixed.
