### ISSUE TITLE
[PE-D][Tester D] MainWindow does not refresh when enrolling a student in multiple courses 

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14B-2/tp#190]
The first `enroll` command seems to work as intended, but the second `enroll` command is executed without adding the additional course enrollment to `Alice`

This might be due to how your listeners are adapted.

![image.png](https://raw.githubusercontent.com/gnoossk/ped/main/files/9950406f-49b1-4ab4-af9f-3423cbc5f366.png)

![image.png](https://raw.githubusercontent.com/gnoossk/ped/main/files/b70f5320-9482-4907-afb7-25c8338f2169.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: gnoossk/ped#6

**Comment by FlyingDonkeys** [comment]
Valid bug, must change listener to update UI whenever a command is entered. Currently the new enrollment is only reflected ```onclick```.
