### ISSUE TITLE
[PE-D][Tester D] Inability to edit attendance

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14B-2/tp#195]
As this app is meant for TA's, there is a likelihood that they will accidentally misclick the attendance Buttons in the gui 

However, there is no way to select a chosen attendance and mark it as present or absent. The application only adds new attendances, but these cannot be modified

Clicking on the first attendance, then trying to mark it as absent 

![image.png](https://raw.githubusercontent.com/gnoossk/ped/main/files/a146af33-8c44-474c-9f8e-67b6c6f02ebf.png)

Just results in another absent attendance

![image.png](https://raw.githubusercontent.com/gnoossk/ped/main/files/1cf8d219-4122-4267-8318-006b718a160c.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: gnoossk/ped#7

**Comment by FlyingDonkeys** [comment]
This use case has been considered and we do have a command that allows TA's to fix mistakes. 

By using the command, 
```attend-remove m/A1234567Y c/CS1101S t/T10A``` 
the TA is able to remove his last attend command and fix his mistakes.

(Note: Why is T10A valid for a tutorial code @Zeepheru)

**Comment by Zeepheru** [comment]
Oh, regarding T10A being valid, it's valid for CS1101S, but not for us lol

Kind of an oversight from my end when writing the example commands, I'll fix it

**Comment by devivy** [comment]
forget
