### ISSUE TITLE
[PE-D][Tester E] person-edit: unexpectedly destroys course association of edited person

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14B-2/tp#205]
On default data:
person-edit m/A1234567X n/Alex Yeo
![image.png](https://raw.githubusercontent.com/sumomomomomo/ped/main/files/9d2e8fc0-826e-4e60-81e6-ce71f2edfd75.png)
^before command

![image.png](https://raw.githubusercontent.com/sumomomomomo/ped/main/files/fcb6f11a-79cd-4f03-832e-91661d8a1753.png)
^after command

His association to CS1010 is now missing. I think behaviour like this that could cause loss of data should have a corresponding warning in the UG. I.e. edit will not preserve course mapping. Or change the implementation of `person-edit` to preserve enrollment

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: sumomomomomo/ped#13

**Comment by FlyingDonkeys** [comment]
In fact, the enrolled courses do not disappear, it can reappear upon reopening the app. @devivy you should ensure that an app reopening is not required though, coz it should be reflected immediately :)
