### ISSUE TITLE
[PE-D][Tester C] Some info in the developer guide is yet to be updated.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14B-2/tp#212]
Some info in the developer guide is yet to be updated.

![image.png](https://raw.githubusercontent.com/arnav-goel10/ped/main/files/68dab409-384c-4536-8c53-f636f50e7dbc.png)

![image.png](https://raw.githubusercontent.com/arnav-goel10/ped/main/files/9c4bca1c-3a35-4d04-bc1f-493fce68fd3b.png)

![image.png](https://raw.githubusercontent.com/arnav-goel10/ped/main/files/4a78b407-f235-4260-b503-e5855714894c.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: arnav-goel10/ped#6

**Comment by FlyingDonkeys** [comment]
Honestly can just remove this section if no time to do lol

**Comment by Zeepheru** [comment]
> Honestly can just remove this section if no time to do lol

Yes
