### ISSUE TITLE
[PE-D][Tester A] Address reads other fields

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14B-2/tp#216]
![Screenshot 2024-11-08 at 5.20.52 PM.png](https://raw.githubusercontent.com/Jollybomber/ped/main/files/da6631ed-6c74-4f90-83cf-836df3ddf443.png)

Parser treats the n/Alex as the address rather than returning an error message.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Jollybomber/ped#12

**Comment by FlyingDonkeys** [comment]
The ```person-edit``` command has the following usage ```person-edit m/MATRICULATION_NUMBER [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [t/TAG]…​​```, by doing ```a/n/Alex```, you are editing the address to be ```n/Alex```, which is accepted by the backend. This is not a bug (although it would be interesting for someone to have such an address LOL).
