### ISSUE TITLE
[PE-D][Tester C] Incorrect prefix in user guide for TUTORIAL_ID

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14B-2/tp#224]
User guide shows incorrect prefix for tutorial id, the prefix is actually tut/

![image.png](https://raw.githubusercontent.com/arnav-goel10/ped/main/files/a373caa0-1a46-416e-9e2b-9d4ad07e4506.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: arnav-goel10/ped#9

**Comment by Zeepheru** [comment]
@FlyingDonkeys got fixed by one of my commits

**Comment by FlyingDonkeys** [comment]
@Zeepheru ok then i wont touch this alr
